# Autogenerated by TypeGG

class_name NodeTreeUtil


static func findAcestorByName(node: Node, name: String) -> Node:
    var foundNode: Node = node.get_node(name)
    if foundNode:
        return foundNode
    var parent: Node = node.get_parent()
    if parent:
        return NodeTreeUtil.findAcestorByName(parent, name)
    return null

