# Autogenerated by TypeGG

class_name Spacehip
extends Sprite2D
@export var myProp: float = [object Object]

func launch() -> void:
    if true:
        print("launch")
        if true:
            print("hello moon")
            if true:
                self.fly()

func fly() -> void:
    var celestialBody: String = "moon"
    print()

func _ready() -> void:
    self.launch()
