# Autogenerated by TypeGG

class_name Spacehip
extends Sprite2D

signal onFoo
signal onBar(bar: String, baz: int)

@export var myProp: int = null
var myInts: Array[int] = [1, 2, 3]
var myNodes: Array[Node]
var myNodes2: Array[Node]
@onready var mySprite: Sprite2D = self.get_node_unsafe("MySprite2D")


func launch() -> void:
    if self.myProp:
        print("launch")
        if true:
            print("hello moon")
            if true:
                self.fly()

func fly() -> void:
    var celestialBody: String = "moon"
    print("fly me to the " + str(celestialBody) + "!\nAnd Back")
    self.onFoo.emit()
    self.onFoo.connect(self.launch)

func _ready() -> void:
    self.launch()

