
/**
 * Custom code to generate previews. Please check `file_dialog/thumbnail_size` in [EditorSettings] to find out the right size to do previews at.
 *
*/
declare class EditorResourcePreviewGenerator extends RefCounted  {

  
/**
 * Custom code to generate previews. Please check `file_dialog/thumbnail_size` in [EditorSettings] to find out the right size to do previews at.
 *
*/
  new(): EditorResourcePreviewGenerator; 
  static "new"(): EditorResourcePreviewGenerator 



/**
 * If this function returns `true`, the generator will call [method _generate] or [method _generate_from_path] for small previews as well.
 *
 * By default, it returns `false`.
 *
*/
protected _can_generate_small_preview(): boolean;

/**
 * Generate a preview from a given resource with the specified size. This must always be implemented.
 *
 * Returning an empty texture is an OK way to fail and let another generator take care.
 *
 * Care must be taken because this function is always called from a thread (not the main thread).
 *
 * [param metadata] dictionary can be modified to store file-specific metadata that can be used in [method EditorResourceTooltipPlugin._make_tooltip_for_path] (like image size, sample length etc.).
 *
*/
protected _generate(): Texture2D;

/**
 * Generate a preview directly from a path with the specified size. Implementing this is optional, as default code will load and call [method _generate].
 *
 * Returning an empty texture is an OK way to fail and let another generator take care.
 *
 * Care must be taken because this function is always called from a thread (not the main thread).
 *
 * [param metadata] dictionary can be modified to store file-specific metadata that can be used in [method EditorResourceTooltipPlugin._make_tooltip_for_path] (like image size, sample length etc.).
 *
*/
protected _generate_from_path(): Texture2D;

/**
 * If this function returns `true`, the generator will automatically generate the small previews from the normal preview texture generated by the methods [method _generate] or [method _generate_from_path].
 *
 * By default, it returns `false`.
 *
*/
protected _generate_small_preview_automatically(): boolean;

/** Returns [code]true[/code] if your generator supports the resource of type [param type]. */
protected _handles(): boolean;

  connect<T extends SignalsOf<EditorResourcePreviewGenerator>>(signal: T, method: SignalFunction<EditorResourcePreviewGenerator[T]>): number;






}

