import { Project } from 'ts-morph'

// TODO: Cleanup
function main() {
  const project = new Project({
    tsConfigFilePath: './tsconfig.json',
  })
  const nodesFile = project.getSourceFileOrThrow('src/grammar/nodes.ts')

  const nodeInterfaces = nodesFile
    .getInterfaces()
    .map((i) => i.getName())
    .filter((name) => name !== 'GDNodeBase')

  const nodesUnionFile =
    project.getSourceFile('src/grammar/nodesUnion.ts') ||
    project.createSourceFile('src/grammar/nodesUnion.ts')

  nodesUnionFile.removeText()
  nodesUnionFile.addStatements(`
// ---
// Autogenerated by buildGrammarTypes.ts
// ---
`)
  nodesUnionFile.addImportDeclaration({
    moduleSpecifier: './kind',
    namedImports: ['GDKind'],
  })
  nodesUnionFile.addImportDeclaration({
    moduleSpecifier: './nodes',
    isTypeOnly: true,
    namedImports: nodeInterfaces,
  })
  nodesUnionFile.addTypeAlias({
    name: 'GDNode',
    type: nodeInterfaces.join(' | '),
    isExported: true,
  })

  for (const nodeInterface of nodeInterfaces) {
    const gdKindName = nodeInterface.replace(/^GD/, '')
    nodesUnionFile.addFunction({
      name: `is${nodeInterface}`,
      isExported: true,
      parameters: [{ name: 'node', type: `GDNode` }],
      returnType: `node is ${nodeInterface}`,
      statements: `return node.kind === GDKind.${gdKindName}`,
    })
  }

  nodesUnionFile.saveSync()
}

main()
