import { GDKind } from '../grammar/kind'
import { GDClass } from '../grammar/nodes'
import { isGDClassProperty, isGDSignal } from '../grammar/nodes-union'
import { line } from '../util/line'

import { renderClassProperty } from './class-property'
import { renderMethod } from './method'

export function renderClass(classNode: GDClass): string {
  const signals = classNode.properties.filter(isGDSignal)
  const properties = classNode.properties.filter(isGDClassProperty)
  const methods = classNode.methods

  return [
    line('# Autogenerated by TypeGG'),
    line(),
    line(`class_name ${classNode.name}`),
    classNode.extends && line(`extends ${classNode.extends}`),
    line(),
    signals.length > 0 && line(...signals.map(renderClassProperty)),
    properties.length > 0 && line(...properties.map(renderClassProperty)),
    methods.length > 0 && line(...classNode.methods.map(renderMethod)),
  ]
    .flat()
    .filter((ln) => ln)
    .join('')
}

if (import.meta.vitest) {
  const { expect, test } = import.meta.vitest

  test('class name', () => {
    expect(
      renderClass({
        kind: GDKind.Class,
        name: 'Foo',
        extends: null,
        properties: [],
        methods: [],
      }),
    ).toEqualGdScript(`
      class_name Foo
    `)
  })

  test('extends', () => {
    expect(
      renderClass({
        kind: GDKind.Class,
        name: 'Foo',
        extends: 'Sprite2D',
        properties: [],
        methods: [],
      }),
    ).toEqualGdScript(`
      class_name Foo
      extends Sprite2D
    `)
  })
}
