import { ClassDeclaration } from 'ts-morph'

import { line } from '../../util/line'

import { parseExpression } from '../expressions/expression'

import { parseClassProperty } from './classProperty'
import { parseMethod } from './method'

export function parseClass(classNode: ClassDeclaration): string {
  const className = classNode.getName()

  const extendsClassExpression = classNode.getExtends()?.getExpression()
  const extendsClassName =
    extendsClassExpression && parseExpression(extendsClassExpression)

  return [
    line('# Autogenerated by TypeGG'),
    line(),
    line(`class_name ${className}`),
    extendsClassName && line(`extends ${extendsClassName}`),
    ...classNode.getProperties().map(parseClassProperty),
    ...classNode.getMethods().map(parseMethod),
  ].join('')
}
